packages:
  - '.'
  - 'packages/uxx'
  - 'packages/webgl-graph-view'
  - 'packages/openplanner-cljs-client'
  - 'packages/opencode-cljs-client'
  - 'packages/aether'
  - 'packages/logger'
  - 'packages/embedding'
  - 'packages/test-utils'
  - 'packages/signal-contracts'
  - 'packages/signal-radar-core'
  - 'packages/event'
  - 'packages/persistence'
  - 'packages/sintel'
  - 'packages/mcp-oauth'
  - 'packages/ollama-queue'
  - 'packages/opencode-interface-plugin'
  - 'packages/personality-system'
  - 'packages/circuits-octave'
  - 'packages/reconstituter'
  - 'packages/opencode-openplanner-plugin-cljs'
  - 'packages/mcp-fs-oauth'
  - 'packages/janus'
  - 'packages/clients'
  - 'packages/cephalon/packages/cephalon-ts'
  - 'packages/cephalon/packages/cephalon-cljs'
  - 'packages/graph-weaver-aco'
  - 'packages/graph-weaver'
  - 'packages/eros-eris-field'
  - 'packages/eros-eris-field-app'
  - 'packages/myrmex'
  - 'packages/knoxx'
  - 'packages/knoxx/frontend'
