packages:
  - '.'
  - 'packages/uxx'
  - 'packages/webgl-graph-view'
  - 'packages/openplanner-cljs-client'
  - 'packages/opencode-cljs-client'
  - 'packages/aether'
  - 'packages/logger'
  - 'packages/mcp-oauth'
  - 'packages/reconstituter'
  - 'packages/opencode-openplanner-plugin-cljs'
  - 'packages/mcp-fs-oauth'
  - 'packages/janus'
  - 'packages/graph-weaver-aco'
  - 'packages/graph-weaver'
  - 'packages/eros-eris-field'
  - 'packages/eros-eris-field-app'
  - 'packages/myrmex'
  - 'packages/knoxx'
  - 'packages/knoxx/frontend'
