import * as readline from 'readline';
import * as fs from 'fs';
import * as path from 'path';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(prompt: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => resolve(answer.trim()));
  });
}

async function setup() {
  console.log('\n🤖 Knoxx Discord Bot Setup\n');
  console.log('This wizard will help you configure your Discord bot.\n');
  console.log('📋 Prerequisites:');
  console.log('   1. Create a Discord application at https://discord.com/developers/applications');
  console.log('   2. Create a bot and copy the Bot Token');
  console.log('   3. Copy the Application ID (Client ID)');
  console.log('   4. Enable "Message Content Intent" in the Bot settings');
  console.log('   5. Optional: Knoxx API key (if your target API requires x-api-key)\n');

  const config: Record<string, string> = {};

  // Discord credentials
  console.log('--- Discord Credentials ---\n');
  
  config.DISCORD_BOT_TOKEN = await question('Discord Bot Token: ');
  if (!config.DISCORD_BOT_TOKEN) {
    console.error('❌ Bot token is required');
    process.exit(1);
  }

  config.DISCORD_CLIENT_ID = await question('Discord Client ID: ');
  if (!config.DISCORD_CLIENT_ID) {
    console.error('❌ Client ID is required');
    process.exit(1);
  }

  config.DISCORD_GUILD_ID = await question('Guild ID (optional, for faster testing): ');

  // RAG Backend
  console.log('\n--- RAG Backend ---\n');
  
  const defaultApiUrl = 'http://localhost:8000/api/knoxx';
  const apiUrl = await question(`RAG API URL [${defaultApiUrl}]: `);
  config.RAG_API_URL = apiUrl || defaultApiUrl;

  config.RAG_API_KEY = await question('Knoxx API Key (optional): ');

  // Bot customization
  console.log('\n--- Bot Customization ---\n');
  
  const defaultBotName = 'Docs Bot';
  const botName = await question(`Bot Name [${defaultBotName}]: `);
  config.BOT_NAME = botName || defaultBotName;

  const defaultPrefix = '!docs';
  const prefix = await question(`Command Prefix [${defaultPrefix}]: `);
  config.BOT_COMMAND_PREFIX = prefix || defaultPrefix;

  const defaultColor = '0x7c3aed';
  const color = await question(`Embed Color (hex) [${defaultColor}]: `);
  config.BOT_EMBED_COLOR = color || defaultColor;

  const defaultCooldown = '5';
  const cooldown = await question(`Cooldown Seconds [${defaultCooldown}]: `);
  config.COOLDOWN_SECONDS = cooldown || defaultCooldown;

  config.LOG_LEVEL = 'info';

  // Write .env file
  const envContent = `# Discord Bot Configuration
# Generated by setup wizard

# Discord Bot Credentials
DISCORD_BOT_TOKEN=${config.DISCORD_BOT_TOKEN}
DISCORD_CLIENT_ID=${config.DISCORD_CLIENT_ID}
DISCORD_GUILD_ID=${config.DISCORD_GUILD_ID}

# RAG Backend
RAG_API_URL=${config.RAG_API_URL}
RAG_API_KEY=${config.RAG_API_KEY}

# Bot Customization
BOT_NAME=${config.BOT_NAME}
BOT_COMMAND_PREFIX=${config.BOT_COMMAND_PREFIX}
BOT_EMBED_COLOR=${config.BOT_EMBED_COLOR}

# Rate Limiting
COOLDOWN_SECONDS=${config.COOLDOWN_SECONDS}

# Logging
LOG_LEVEL=${config.LOG_LEVEL}
`;

  const envPath = path.join(process.cwd(), '.env');
  fs.writeFileSync(envPath, envContent);

  console.log('\n✅ Configuration saved to .env\n');
  console.log('Next steps:');
  console.log('  1. Run `npm run register` to register slash commands');
  console.log('  2. Run `npm run dev` to start the bot in development mode');
  console.log('  3. Or run `npm run build && npm start` for production\n');

  rl.close();
}

setup().catch((error) => {
  console.error('Setup failed:', error);
  rl.close();
  process.exit(1);
});
